### ISSUE TITLE
skooter could login but unable to submit a score and view leaderboard

### ISSUE THREAD

**Issue by remeliah** [kawatapw/kawata.py#2]
### Describe the bug

skooter is able to login to the serv. but, when i try to submit a score and view the leaderboard, it just doesnt work
![screenshot130](https://github.com/kawatapw/kawata.py/assets/132663728/fe89f609-8cc4-4725-b3fc-4ccd61342eed)
![screenshot131](https://github.com/kawatapw/kawata.py/assets/132663728/17cc84f4-72e7-44a4-b2c0-c99be8ab5e39)

### To Reproduce

1. login to the server using skooterb5 or any skooter version (tls patched or something like that)
2. try to submit a score 
3. see the leaderboard

### Expected behavior

skooter should be able to submit a score and view the leaderboard after logging in.

### bancho.py Version

d

### Python Version

3.11.X (Default)

**Comment by TheFantasticLoki** [comment]
Leaderboards have been resolved with a redirect of /web/ requests to osu.kawata.pw from root url kawata.pw
Score Submission has been fixed in commit 3d00078
